### ISSUE TITLE
Case-sensitive when creating table

### ISSUE THREAD

**Issue by dhabierre** [b00ted/serilog-sinks-postgresql#17]
Hi,

Thanks for this sink, it is great!

In my case, all my tables and column names must be Pascal case.
But when the table is created, the table & colums names are lowercase letters.

To respect the case-sensitive we need to use double quotes around the names.

I am going to submit a Pull Request to add this feature.
By default, the behavior is not modified (not to create breaking change with the current one)

**Comment by dhabierre** [comment]
[Pull Request](https://github.com/b00ted/serilog-sinks-postgresql/pull/18)

**Comment by SeppPenner** [comment]
You could use my new project which is basically the same as this repo but will be better maintained: https://github.com/SeppPenner/SerilogSinkForPostgreSQL. Don't hesitate to put this pull request to my repository, too.

**Comment by regul4rj0hn** [comment]
I think that this issue is related. Even when configuring the sink to use PascalCase table names, it attempts to read them as lowercase:
```
"schemaName":  "dbo",
"tableName": "Logs"
```
So I get an exception on self-log:

`Exception while emitting periodic batch from Serilog.Sinks.PostgreSQL.PostgreSQLSink: Npgsql.PostgresException (0x80004005): 42P01: relation "dbo.logs" does not exist`

Of course that if I set `needAutoCreateTable` everything works, but it creates lowercase objects that don't comply with my team's design guidelines.

**Comment by SeppPenner** [comment]
@regul4rj0hn: Sure, this is related. I've tried to add this feature to my project: https://github.com/SeppPenner/SerilogSinkForPostgreSQL. However, it somehow still fails and I did not find the error case by now. Stay tuned for updates, I will try to add this feature to my project as soon as possible.

**Comment by b00ted** [comment]
Added in version 2.1.0

**Comment by okanulkr** [comment]
I was able to solve issue by using **escaped quotes**. Use columns configuration like below:

Columns: {
**"\\"PascalCasedColumn\\""**: "RenderedMessageColumnWriter", `// will be **PascalCasedColumn** on database.`
"LowerCasedColumn": "RenderedMessageColumnWriter" `// will be **lowercasedcolumn** on database.`
}
